name: Windows Build

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - '.github/workflows/windows_build.yml'
      - 'windows/**'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Clone Rust library repository
      - name: Clone Rust library repository
        run: |
          git clone https://github.com/mobile247/activity-monitor.git rust_lib
      
      # Build Rust library for Windows
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      # Fix the Windows build error
      - name: Fix Windows build error
        run: |
          $windowsPath = "rust_lib\src\windows.rs"
          $content = Get-Content -Path $windowsPath
          
          # Update keyboard hook
          $content = $content -replace "KEYBOARD_HOOK = Some\(SetWindowsHookExW\(", "KEYBOARD_HOOK = Some(SetWindowsHookExW("
          $content = $content -replace "\|\s*\)\)\);", "| )).expect(""Failed to set keyboard hook""));"
          
          # Update mouse hook
          $content = $content -replace "MOUSE_HOOK = Some\(SetWindowsHookExW\(", "MOUSE_HOOK = Some(SetWindowsHookExW("
          $content = $content -replace "\|\s*\)\)\);", "| )).expect(""Failed to set mouse hook""));"
          
          # Fix unused variable warning
          $content = $content -replace "let is_genuine", "let _is_genuine"
          
          Set-Content -Path $windowsPath -Value $content
      
      - name: Build Rust DLL
        run: |
          cd rust_lib
          cargo build --release
      
      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'
      
      # Enable Windows desktop
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      
      # Create a completely separate Flutter project with the correct name
      - name: Create separate Flutter project
        run: |
          # Create a temp directory for the valid-named Flutter project
          mkdir -p C:\temp_flutter_project
          cd C:\temp_flutter_project
          
          # Create a new Flutter project with Windows support
          flutter create --platforms=windows activity_monitor_app
          
          # Copy over the relevant files from the original project
          cd activity_monitor_app
          
          # Copy the library files from the main project
          Copy-Item -Path "${{ github.workspace }}\lib\*" -Destination "lib\" -Recurse -Force
      
      # Create a minimal plugin to integrate the Rust DLL
      - name: Create Rust DLL plugin
        run: |
          cd C:\temp_flutter_project\activity_monitor_app
          
          # Create windows folder if it doesn't exist
          mkdir -p windows
          
          # Create lib directory for the DLL
          mkdir -p windows\lib
          
          # Copy the DLL
          Copy-Item -Path "${{ github.workspace }}\rust_lib\target\release\activity_monitor.dll" -Destination "windows\lib\"
          
          # Instead of adding to CMakeLists.txt, create a batch file to copy the DLL after build
          $batchFile = @"
          @echo off
          echo Copying activity_monitor.dll to build directory...
          copy /Y "%~dp0\windows\lib\activity_monitor.dll" "%~dp0\build\windows\runner\Release\"
          echo Done!
          "@
          
          Set-Content -Path "copy_dll.bat" -Value $batchFile
      
      # Build the Windows app
      - name: Build Windows app
        run: |
          cd C:\temp_flutter_project\activity_monitor_app
          flutter pub get
          flutter build windows --release
          
          # Run the batch file to copy the DLL
          .\copy_dll.bat
      
      # Copy the built files back to the workspace
      - name: Copy built files to workspace
        run: |
          # Create directory for the built files
          mkdir -p ${{ github.workspace }}\build\windows\runner\Release
          
          # Copy the built files
          Copy-Item -Path "C:\temp_flutter_project\activity_monitor_app\build\windows\runner\Release\*" -Destination "${{ github.workspace }}\build\windows\runner\Release\" -Recurse -Force
      
      # Zip the Windows build
      - name: Create Windows build archive
        run: |
          cd ${{ github.workspace }}
          Compress-Archive -Path "build\windows\runner\Release\*" -DestinationPath "activity_monitor_windows_build.zip"
      
      # Upload the Windows build
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: activity_monitor_windows_build
          path: activity_monitor_windows_build.zip
          retention-days: 7